# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/austin/robodog/zybo_z7-20/vivado_2020_2/Zybo-Z7-Master.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# XDC: /home/austin/robodog/zybo_z7-20/vivado_2020_2/led_switch_test/led_switch_test.gen/sources_1/bd/design_1/design_1_ooc.xdc
